name: Pull Request
# Run terraform plan on pull requests to master

on:
  pull_request:
    branches: [ master ]


jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-20.04
    container:
      image: darthfork/dorker:fedora35
      env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      options:
        --user 0:0
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      id: init
      run: make -C terraform init

    - name: Build Vars
      id: vars
      run: ./build_tfvars.sh

    - name: Terraform Plan
      id: plan
      run: make -C terraform plan_nc

    - name: Terraform Publish
      id: publish
      uses: actions/github-script@0.9.0
      env:
        STDOUT: "```${{ steps.plan.outputs.stdout }}```"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.STDOUT
          })

    - name: Infracost Diff
      id: infracost
      uses: infracost/infracost-gh-action@master
      with:
        entrypoint: /scripts/ci/diff.sh
        path: terraform
        terraform_plan_flags: -var-file=terraform.tfvars
