name: Push Commit
# Run terraform plan and terraform apply on commits to main

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.tf'

jobs:
  terraform_apply:
    name: Terraform Plan and Apply
    environment: production
    runs-on: ubuntu-20.04
    env:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
      SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
      AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      id: setup
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version: 1.4.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/github_oidc_role
        aws-region: ${{ env.AWS_REGION }}

    - name: Build Vars
      id: vars
      shell: bash
      run: ./build_tfvars.sh

    - name: Terraform Init
      id: init
      run: make -C terraform init

    - name: Terraform Plan
      id: plan
      run: make -C terraform plan_nc

    - name: Terraform Apply
      id: apply
      run: make -C terraform apply

    - name: Terraform Publish
      id: publish
      uses: actions/github-script@v6
      env:
        STDOUT: "```${{ steps.plan.outputs.stdout }}```"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: process.env.STDOUT
          })
